config/routes.rb
class AdminConstraint
  def self.matches?(request)
    if request.session[:user_id]
      user = User.find request.session[:user_id]
      user && user.admin?
    end
  end
end

Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post 'markdown/preview', to: 'markdown#preview'

  resources :users, only: [:create] do
    collection do
      get :check_email
      get :check_username
    end
  end

  namespace :users do
    resource :password, only: [:show, :new, :create, :edit, :update]
    resource :confirmation, only: [:new, :show, :create]
  end

  concern :commentable do
    resources :comments, only: [:create]
  end

  concern :likeable do
    resource :like, only: [:create, :destroy]
  end

  concern :subscribable do
    resource :subscription, only: [:update, :destroy]
  end

  resources :topics, only: [:index, :show, :new, :create, :edit, :update], concerns: [:commentable, :likeable, :subscribable] do
    collection do
      get 'categoried/:category_id', to: 'topics#index', as: :categoried
      get 'search'
    end

    member do
      delete :trash
    end
  end

  resources :comments, only: [:edit, :update], concerns: [:likeable] do
    member do
      get :cancel
      delete :trash
    end
  end

  resources :notifications, only: [:index, :destroy] do
    collection do
      post :mark
      delete :clear
    end
  end

  resources :attachments, only: [:create]

  root 'topics#index'

  scope path: '~:username', module: 'users', as: 'user' do
    resources :topics, only: [:index] do
      collection do
        get :likes
      end
    end
    resources :comments, only: [:index] do
      collection do
        get :likes
      end
    end

    resources :invitations, only: [:index, :create]
    get '/invitations/:invitation_code', to: 'invitations#show'

    root to: 'topics#index'
  end

  namespace :settings do
    resource :account, only: [:show, :update]
    resource :password, only: [:show, :update]
    resource :profile, only: [:show, :update]
    resource :notifications, only: [:show, :update]
  end

  namespace :admin do
    root to: 'dashboard#show'

    resources :users, only: [:index, :show, :update, :destroy] do
      collection do
        get :locked
      end

      member do
        patch :lock
        delete :lock, action: 'unlock'
      end
    end

    resources :categories, except: [:edit]

    resources :topics, only: [:index, :show, :update] do
      collection do
        get :trashed
      end

      member do
        delete :trash
        patch :restore
      end
    end

    resources :comments, only: [:index, :show, :update] do
      collection do
        get :trashed
      end

      member do
        delete :trash
        patch :restore
      end
    end

    resources :attachments, only: [:index, :destroy]
  end

  constraints(AdminConstraint) do
    mount Resque::Server.new, at: 'resque'
  end

  if Rails.env.development?
    get 'qunit', to: 'qunit#index'
  end
end

app/controllers/settings/accounts_controller.rb
class Settings::AccountsController < Settings::ApplicationController
  before_action :current_password_required, only: [:update]

  def show
  end

  def update
    if @user.update_attributes params.require(:user).permit(:username, :email, :locale)
      flash[:success] = I18n.t('settings.accounts.flashes.successfully_updated')
      redirect_to settings_account_path
    else
      render :show
    end
  end
end

app/controllers/settings/application_controller.rb
class Settings::ApplicationController < ApplicationController
  before_action :login_required, :set_user

  private

  def set_user
    @user = current_user
  end

  def current_password_required
    unless params[:current_password] && @user.authenticate(params[:current_password])
      flash.now[:warning] = I18n.t('settings.flashes.incorrect_current_password')
      render :show
    end
  end
end

app/controllers/settings/notifications_controller.rb
class Settings::NotificationsController < Settings::ApplicationController
  def show
  end

  def update
    if @user.update_attributes params.require(:user).permit(:send_mention_email, :send_mention_web, :send_comment_email, :send_comment_web)
      flash[:success] = I18n.t('settings.notifications.flashes.successfully_updated')
      redirect_to settings_notifications_url
    else
      render :show
    end
  end
end

app/controllers/settings/passwords_controller.rb
class Settings::PasswordsController < Settings::ApplicationController
  before_action :current_password_required, only: [:update]

  def show
  end

  def update
    if @user.update_attributes params.require(:user).permit(:password, :password_confirmation)
      flash[:success] = I18n.t('settings.passwords.flashes.successfully_updated')
      redirect_to settings_password_url
    else
      render :show
    end
  end
end

app/controllers/settings/profiles_controller.rb
class Settings::ProfilesController < Settings::ApplicationController
  def show
  end

  def update
    if @user.update_attributes params.require(:user).permit(:name, :bio, :avatar, :remove_avatar)
      flash[:success] = I18n.t('settings.profiles.flashes.successfully_updated')
      redirect_to settings_profile_url
    else
      render :show
    end
  end
end

app/views/settings/profiles/show.html.slim
- @page_title = t '.profile_settings'

.main
  .container
    .row
      .col-md-3
        = render 'settings/sidebar'
      .col-md-9
        .panel
          .panel-heading
            h3.panel-title
              = t '.profile'
          .panel-body
            = form_for @user, url: settings_profile_path, html: { multipart: true, class: 'form-horizontal user-form' } do |f|
              = render 'share/flash_messages'
              = render 'share/form_error_messages', form: f
              .form-group
                = f.label :avatar, class: 'control-label col-sm-3'
                .col-sm-6.user-image-uploader
                  .image
                    img.img-rounded alt="avatar" src=current_user.avatar.bigger.url
                  .uploader
                    = f.file_field :avatar, tabIndex: 1
                    .checkbox
                      label
                        = f.check_box :remove_avatar, tabIndex: 2
                        '
                        | Remove avatar
              .form-group
                = f.label :name, class: 'control-label col-sm-3'
                .col-sm-6
                  = f.text_field :name, class: 'form-control', tabIndex: 3
              .form-group
                = f.label :bio, class: 'control-label col-sm-3'
                .col-sm-6
                  = f.text_area :bio, class: 'form-control', tabIndex: 4
              .form-group
                .col-sm-6.col-sm-push-3
                  = f.submit t('.save_changes'), class: 'btn btn-primary', tabIndex: 5

javascript:
  $('form.user-form').validate({
    rules: {
      'user[name]': {
        required: true,
      }
    },
    messages: {
      'user[name]': {
        required: '#{@user.errors.generate_message :name, :blank}'
      }
    }
  });